# SPDX-FileCopyrightText: 2024 Henrik Jakob jakob@ibb.uni-stuttgart.de
# SPDX-License-Identifier: MIT

version: "3.3"
services:
  OpenIkarusContainer-clang:
    image: henrij22/dunebase-clang-iwyu:latest
    entrypoint: /bin/bash
    tty: true
    user: root
    volumes: 
      - .:/workspaces/dune-iga
    working_dir: /workspaces/dung-iga
